name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Remove large files (if any)
        run: |
          git filter-repo --invert-paths --path Rag_Documents/layout-parser-paper.pdf || true

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://sushantsur23:${HF_TOKEN}@huggingface.co/spaces/sushantsur23/Routing_Agentic_AI_Workflow

      - name: Push code (with Dockerfile) to Hugging Face Space
        run: |
          git push --force origin main
